name: CI Dev

on:
  push:
    branches: [ 'dev', 'staging', 'production' ]
  pull_request: 
    branches: [ 'staging' , 'dev', 'production' ]

jobs:
  build-and-test:
    runs-on: ubunutu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup_node@v4
        with: 
          node-version : '20.x'
      - run: npm ci
      - run: npm run test
