name: Deploy Staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devOpsExample

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
        
      - run: npm ci
 
      - name: Build staging app
        run: eas build --platform android --profile preview --non-interactive
